version: '3.8'
services:
  app:
    build: .
    container_name: flixtr-prod
    restart: unless-stopped
    networks:
      - nginx-proxy
    env_file:
      - .env.production

networks:
  nginx-proxy:
    external: true