export const styles = {
  modalBox: {
    outline: "none",
    border: "4px solid",
    borderColor: "secondary.main",
    borderRadius: "8px",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "95%",
    maxWidth: "400px",
    backgroundColor: "primary.main",
    boxShadow: 24,
    p: 4,
    textAlign: "center",
  },
  modalDesc: { mt: 2 },
  modalBtn: { mt: 3 },
};
