name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Dev server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/ubuntu/Desktop/flixtr-fe-dev

          # Discard local changes to package-lock.json or other files etc
          git reset --hard HEAD

          git pull origin dev
          echo "${{ secrets.DEV_ENV }}" > .env.dev
          docker-compose -f docker-compose.dev.yml down && docker-compose -f docker-compose.dev.yml up -d --build
          docker system prune -f
          EOF
