name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Dev server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'

          # Ensure nvm is sourced
          source /home/ubuntu/.nvm/nvm.sh

          cd /home/ubuntu/Desktop/flixtr-fe-dev
          git pull origin dev
          npm install
          rm .env
          echo "${{ secrets.DEV_ENV }}" > .env
          npm run build
          pm2 restart flixtr-dev
          EOF
